name: in_code
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  another_flushbar: ^1.12.30
  intl: ^0.20.2
  auto_size_text: ^3.0.0
  iconsax: ^0.0.8
  animate_do: ^4.2.0
  flutter_custom_clippers: ^2.1.0
  enefty_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^6.1.4
  lottie: ^3.3.0
  mobile_scanner: ^7.0.1
  url_launcher: ^6.3.1
  # screen_brightness: ^2.1.5
  form_field_validator: ^1.1.0
  vibration: ^3.1.3
  flutter_localizations:
    sdk: flutter
  package_info_plus: ^8.3.0
  permission_handler: 
  permission_guard: ^2.0.1
  app_settings: ^5.1.1
  syncfusion_flutter_datepicker: ^30.1.42
  pdf: ^3.10.4
  printing: ^5.11.0
  excel: ^4.0.6
  path_provider: ^2.1.1
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  android_adaptive_icon: false


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/scan.json

flutter_native_splash:
  color: "#FFC61323"
  image: assets/images/logo.png
  android: true
  ios: true
  fullscreen: true
